### ISSUE TITLE
[BUG] No valid sample data was found.

### ISSUE THREAD

**Issue by spessasus** [sinshu/meltysynth#49]
SoundFont doesn't load in meltysynth, but loads fine in other synthesizers.
The code that throws the exception:
```csharp
using MeltySynth;
using NAudio.Wave;
public class MyWaveProvider : IWaveProvider
{
    private readonly int sampleRate;
    private readonly int channels;
    private int sampleIndex;
    private short[] leftChannelBuffer;
    private short[] rightChannelBuffer;
    private Synthesizer synth;
    private MidiFileSequencer sequencer;

    public MyWaveProvider(int sampleRate, int channels)
    {
        this.sampleRate = sampleRate;
        this.channels = channels;
        this.WaveFormat = WaveFormat.CreateCustomFormat(WaveFormatEncoding.Pcm, sampleRate, channels, sampleRate * channels * 2, channels * 2, 16);
        this.leftChannelBuffer = new short[sampleRate];
        this.rightChannelBuffer = new short[sampleRate];

        // *crashes here*
        this.synth = new Synthesizer("Z:\\_moje_prace\\JavaScript\\SpessaSynth\\soundfonts\\HiDef.sf2", sampleRate);
```
logs:
```
Unhandled exception. System.IO.InvalidDataException: No valid sample data was found.
   at MeltySynth.SoundFontSampleData..ctor(BinaryReader reader)
   at MeltySynth.SoundFont.Load(Stream stream)
   at MeltySynth.SoundFont..ctor(String path)
   at MeltySynth.Synthesizer..ctor(String soundFontPath, Int32 sampleRate)
   at MyWaveProvider..ctor(Int32 sampleRate, Int32 channels) in Melty_test\SampleProvider.cs:line 21
   at Program.Main() in Melty_test\Program.cs:line 11

```
[The soundfont in question](https://musical-artifacts.com/artifacts/2525)

**Comment by sinshu** [comment]
This issue is due to the sound font size exceeding 2GB. To resolve this problem, it would be necessary to review the overall structure of the code, so I do not intend to address it.
